"""H7: the OIDC login must be bound to the browser (encrypted state cookie) and carry PKCE
(S256) + a nonce, using MSAL's native auth-code-flow (`initiate_auth_code_flow` /
`acquire_token_by_auth_code_flow`) instead of a handrolled, unbound `state` JWT.

Attack-oriented:
- A callback that arrives WITHOUT the browser-bound flow cookie is refused before the token
  exchange is even attempted (login-CSRF / stale or replayed callback).
- The redirect to Entra carries PKCE (`code_challenge`/`code_challenge_method=S256`) and a
  `nonce` -- both generated by MSAL itself, never touched by application code.
- The `code_verifier` MSAL generated during `initiate_login` is exactly what MSAL receives
  back at the token exchange (proves PKCE is wired end-to-end without a live Entra).
- A `state` mismatch at the exchange is rejected (`AuthError`, code `sso_state_mismatch`) --
  non-vacuous: the same flow with the CORRECT state proceeds past the check.
- A legitimate flow (cookie + matching state, network mocked) issues a session and clears the
  flow cookie.

`ConfidentialClientApplication.__init__` unconditionally performs a tenant-discovery HTTP call
(verified empirically against msal 1.37.0 -- "we always do a tenant discovery", `authority.py`;
`validate_authority=False` only skips the separate INSTANCE discovery). To keep this suite
network-independent (like `test_graph_pooling.py`/`test_graph_group_members.py`, which already
stub MSAL's network surface in this repo), `_no_network_tenant_discovery` stubs that one call;
everything else (PKCE/nonce/state generation, the real MSAL state-mismatch check) runs for real.
"""

from __future__ import annotations

from collections.abc import AsyncGenerator, Iterator
from http.cookies import SimpleCookie
from typing import Any
from unittest.mock import AsyncMock, Mock, patch

import msal
import msal.authority
import pytest
import pytest_asyncio
from app.api.deps import OIDC_FLOW_COOKIE, limiter, set_oidc_flow_cookie
from app.api.routes.auth import oidc_callback
from app.core.errors import AuthError
from app.db.session import get_session_factory
from app.repositories import user_repo
from app.services import oidc
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession
from starlette.responses import RedirectResponse, Response

_TEST_DOMAIN = "@pkcestate.test"
_REDIRECT_URI = "https://pwnotify.test/api/auth/oidc/callback"
_SETTINGS: dict[str, Any] = {
    "oidc.enabled": True,
    "graph.tenant_id": "pkce-test-tid",
    "graph.client_id": "pkce-test-client-id",
    "graph.client_secret": "pkce-test-secret",
    "graph.cloud": "global",
    "oidc.admin_group_id": "pkce-admins",
    "oidc.auditor_group_id": "",
}

_FAKE_OIDC_CONFIG = {
    "authorization_endpoint": "https://login.microsoftonline.com/pkce-test-tid/oauth2/v2.0/authorize",
    "token_endpoint": "https://login.microsoftonline.com/pkce-test-tid/oauth2/v2.0/token",
    "issuer": "https://login.microsoftonline.com/pkce-test-tid/v2.0",
}


@pytest.fixture(autouse=True)
def _no_network_tenant_discovery() -> Iterator[None]:
    with patch("msal.authority.tenant_discovery", return_value=_FAKE_OIDC_CONFIG):
        yield


@pytest.fixture(autouse=True)
def _limiter_disabled() -> Iterator[None]:
    """`oidc_callback` is now `@limiter.limit`-decorated (audit I4). slowapi's wrapper insists on
    a real `starlette.requests.Request` when enabled, which the duck-typed `_FakeRequest` used by
    the direct-call tests here is not; disabling the limiter keeps these unit-level tests focused
    on the flow logic. The 429 behaviour is proven over real HTTP in `test_oidc_form_post`."""
    prev = limiter.enabled
    limiter.enabled = False
    try:
        yield
    finally:
        limiter.enabled = prev


class _FakeRequest:
    """Duck-typed Request -- `oidc_callback`/`audit.record` read only these attributes."""

    def __init__(self, cookies: dict[str, str] | None = None) -> None:
        self.headers: dict[str, str] = {}
        self.client: object | None = None
        self.cookies: dict[str, str] = cookies or {}


def _extract_cookie(resp: RedirectResponse, name: str) -> str | None:
    for raw in resp.headers.getlist("set-cookie"):
        jar: SimpleCookie = SimpleCookie()
        jar.load(raw)
        if name in jar:
            return jar[name].value
    return None


def _cookie_cleared(resp: RedirectResponse, name: str) -> bool:
    for raw in resp.headers.getlist("set-cookie"):
        if raw.startswith(f"{name}=") and "Max-Age=0" in raw:
            return True
    return False


# ---- 1. No flow cookie -> rejected before the exchange is even attempted --------------- #


async def test_callback_without_flow_cookie_is_rejected(session: AsyncSession) -> None:
    request = _FakeRequest()  # no OIDC_FLOW_COOKIE set
    exchange_mock = AsyncMock()
    with patch("app.services.oidc.exchange_and_verify", new=exchange_mock):
        resp = await oidc_callback(
            request,  # type: ignore[arg-type]
            session,
            code="fake-code",
            state="some-state",
            error=None,
        )
    assert isinstance(resp, RedirectResponse)
    assert "sso_error=1" in resp.headers["location"]
    exchange_mock.assert_not_called()
    assert _extract_cookie(resp, "pwnotify_access") is None


# ---- 2. The auth redirect carries PKCE S256 + nonce; the flow cookie round-trips ------- #


def test_initiate_login_emits_pkce_and_nonce() -> None:
    auth_url, cookie = oidc.initiate_login(_SETTINGS, _REDIRECT_URI)

    assert "code_challenge=" in auth_url
    assert "code_challenge_method=S256" in auth_url
    assert "nonce=" in auth_url

    flow = oidc.decode_flow_cookie(cookie)
    assert "code_verifier" in flow
    assert "nonce" in flow
    assert "state" in flow


def test_initiate_login_requests_form_post_response_mode() -> None:
    """RFC 9700 §4.3.1: the auth-code flow must be started with `response_mode=form_post` so Entra
    returns the code in a cross-site POST body, not the redirect URL. Red against the old code,
    which passed no `response_mode`."""
    fake_flow = {"auth_uri": "https://login.example/authorize", "state": "s", "nonce": "n"}
    with patch.object(
        msal.ConfidentialClientApplication,
        "initiate_auth_code_flow",
        return_value=fake_flow,
    ) as mock_initiate:
        oidc.initiate_login(_SETTINGS, _REDIRECT_URI)

    assert mock_initiate.call_args.kwargs["response_mode"] == "form_post"


def test_flow_cookie_is_samesite_none_and_secure() -> None:
    """The flow cookie must be `SameSite=None; Secure`: with form_post the callback is a cross-site
    POST, on which a `SameSite=Lax` cookie is NOT sent, and `SameSite=None` mandates `Secure`
    (HTTPS-only SSO). Red against the old code, which set `SameSite=Lax` and `Secure` only when
    `settings.cookie_secure`."""
    resp = Response()
    set_oidc_flow_cookie(resp, "encrypted-flow-value")

    raw = next(
        h for h in resp.headers.getlist("set-cookie") if h.startswith(f"{OIDC_FLOW_COOKIE}=")
    )
    lowered = raw.lower()
    assert "samesite=none" in lowered
    assert "secure" in lowered


# ---- 3. The code_verifier MSAL generated is what MSAL receives back at the exchange ---- #


async def test_code_verifier_sent_on_exchange() -> None:
    _, cookie = oidc.initiate_login(_SETTINGS, _REDIRECT_URI)
    flow = oidc.decode_flow_cookie(cookie)

    mock_acquire = Mock(
        return_value={
            "access_token": "fake-access-token",
            "id_token_claims": {
                "preferred_username": f"alice{_TEST_DOMAIN}",
                "name": "Alice",
                "tid": _SETTINGS["graph.tenant_id"],
                "groups": [_SETTINGS["oidc.admin_group_id"]],
            },
        }
    )
    auth_response = {"code": "c", "state": flow["state"]}
    with patch.object(
        msal.ConfidentialClientApplication, "acquire_token_by_auth_code_flow", new=mock_acquire
    ):
        result = await oidc.exchange_and_verify(_SETTINGS, flow, auth_response)

    mock_acquire.assert_called_once_with(flow, auth_response)
    assert result.username == f"alice{_TEST_DOMAIN}"
    assert result.allowed is True


# ---- 4. State mismatch rejected; correct state proceeds (non-vacuous) ------------------ #


async def test_state_mismatch_rejected() -> None:
    _, cookie = oidc.initiate_login(_SETTINGS, _REDIRECT_URI)
    flow = oidc.decode_flow_cookie(cookie)

    with pytest.raises(AuthError) as exc_info:
        await oidc.exchange_and_verify(_SETTINGS, flow, {"code": "c", "state": "WRONG-STATE"})
    assert exc_info.value.code == "sso_state_mismatch"

    # Non-vacuous: the SAME flow with the CORRECT state (network mocked) proceeds.
    mock_acquire = Mock(
        return_value={
            "access_token": "fake-access-token",
            "id_token_claims": {
                "preferred_username": f"bob{_TEST_DOMAIN}",
                "tid": _SETTINGS["graph.tenant_id"],
                "groups": [_SETTINGS["oidc.admin_group_id"]],
            },
        }
    )
    with patch.object(
        msal.ConfidentialClientApplication, "acquire_token_by_auth_code_flow", new=mock_acquire
    ):
        result = await oidc.exchange_and_verify(
            _SETTINGS, flow, {"code": "c", "state": flow["state"]}
        )
    assert result.username == f"bob{_TEST_DOMAIN}"


# ---- 5. Legitimate flow: session issued, flow cookie cleared --------------------------- #


class _Env:
    tenant_id: int


@pytest_asyncio.fixture
async def pkce_tenant(migrated_engine: AsyncEngine) -> AsyncGenerator[_Env]:
    """Default tenant configured to match `_SETTINGS`, so the callback's `tid`==`graph.tenant_id`
    bootstrap fallback (Task 4, tenant mapping) resolves it and the admin group grants access."""
    async with migrated_engine.connect() as conn:
        default_id = (
            await conn.execute(text("SELECT id FROM tenant WHERE slug = 'default'"))
        ).scalar_one()
        await conn.execute(
            text(
                "INSERT INTO setting (tenant_id, key, value, is_secret, updated_at) VALUES "
                "(:tid, 'oidc.enabled', to_jsonb(true), false, now()), "
                "(:tid, 'graph.tenant_id', to_jsonb(CAST(:entra_tid AS text)), false, now()), "
                "(:tid, 'graph.client_id', to_jsonb(CAST(:client_id AS text)), false, now()), "
                "(:tid, 'graph.client_secret', to_jsonb(CAST(:secret AS text)), true, now()), "
                "(:tid, 'oidc.admin_group_id', to_jsonb(CAST(:group_id AS text)), false, now())"
            ),
            {
                "tid": default_id,
                "entra_tid": _SETTINGS["graph.tenant_id"],
                "client_id": _SETTINGS["graph.client_id"],
                "secret": _SETTINGS["graph.client_secret"],
                "group_id": _SETTINGS["oidc.admin_group_id"],
            },
        )
        await conn.commit()
        fx = _Env()
        fx.tenant_id = default_id
        try:
            yield fx
        finally:
            await conn.execute(
                text(f"DELETE FROM audit_log WHERE actor_username LIKE '%{_TEST_DOMAIN}'")
            )
            await conn.execute(
                text(
                    "DELETE FROM user_session WHERE user_id IN "
                    f"(SELECT id FROM app_user WHERE username LIKE '%{_TEST_DOMAIN}')"
                )
            )
            await conn.execute(text(f"DELETE FROM app_user WHERE username LIKE '%{_TEST_DOMAIN}'"))
            await conn.execute(
                text(
                    "DELETE FROM setting WHERE tenant_id = :tid AND key IN "
                    "('oidc.enabled', 'graph.tenant_id', 'graph.client_id', "
                    "'graph.client_secret', 'oidc.admin_group_id')"
                ),
                {"tid": default_id},
            )
            await conn.execute(
                text("UPDATE tenant SET entra_tenant_id = NULL WHERE id = :tid"),
                {"tid": default_id},
            )
            await conn.commit()


async def test_legit_flow_succeeds(pkce_tenant: _Env) -> None:
    auth_url, cookie = oidc.initiate_login(_SETTINGS, _REDIRECT_URI)
    assert "code_challenge=" in auth_url  # sanity: same flow the browser would have followed
    flow = oidc.decode_flow_cookie(cookie)
    request = _FakeRequest(cookies={OIDC_FLOW_COOKIE: cookie})

    mock_acquire = Mock(
        return_value={
            "access_token": "fake-access-token",
            "id_token_claims": {
                "preferred_username": f"carol{_TEST_DOMAIN}",
                "name": "Carol",
                "tid": _SETTINGS["graph.tenant_id"],
                "groups": [_SETTINGS["oidc.admin_group_id"]],
            },
        }
    )
    session_factory = get_session_factory()
    with patch.object(
        msal.ConfidentialClientApplication, "acquire_token_by_auth_code_flow", new=mock_acquire
    ):
        async with session_factory() as session:
            resp = await oidc_callback(
                request,  # type: ignore[arg-type]
                session,
                code="fake-code",
                state=flow["state"],
                error=None,
            )

    assert isinstance(resp, RedirectResponse)
    assert "sso_denied" not in resp.headers["location"]
    assert "sso_error" not in resp.headers["location"]
    assert _extract_cookie(resp, "pwnotify_access") is not None
    assert _cookie_cleared(resp, OIDC_FLOW_COOKIE), "flow cookie must be cleared on success"

    async with session_factory() as session:
        user = await user_repo.get_by_username(session, f"carol{_TEST_DOMAIN}")
        assert user is not None
        assert user.role == "admin"
