"""initial schema

Revision ID: c92a9a84bc1e
Revises:
Create Date: 2026-07-13 12:51:36.710513
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c92a9a84bc1e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=150), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_app_user_username"), "app_user", ["username"], unique=True)
    op.create_table(
        "entra_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entra_id", sa.String(length=64), nullable=False),
        sa.Column("upn", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=320), nullable=False),
        sa.Column("mail", sa.String(length=320), nullable=True),
        sa.Column("other_mails", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("account_enabled", sa.Boolean(), nullable=False),
        sa.Column("department", sa.String(length=200), nullable=True),
        sa.Column("job_title", sa.String(length=200), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.Column("last_password_change", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_policies", sa.String(length=200), nullable=True),
        sa.Column("password_never_expires", sa.Boolean(), nullable=False),
        sa.Column("expiry_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("days_left", sa.Integer(), nullable=True),
        sa.Column("excluded", sa.Boolean(), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entra_user_entra_id"), "entra_user", ["entra_id"], unique=True)
    op.create_index(op.f("ix_entra_user_upn"), "entra_user", ["upn"], unique=False)
    op.create_table(
        "exclusion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("value", sa.String(length=320), nullable=False),
        sa.Column("label", sa.String(length=320), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("checked_users", sa.Integer(), nullable=False),
        sa.Column("sent", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("skipped", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(length=2000), nullable=True),
        sa.Column("detail_log", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "setting",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_secret", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "notification_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entra_user_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("reminder_day", sa.Integer(), nullable=False),
        sa.Column("expiry_cycle", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("backend", sa.String(length=16), nullable=False),
        sa.Column("recipient", sa.String(length=320), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["entra_user_id"],
            ["entra_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entra_user_id", "reminder_day", "expiry_cycle", name="uq_notif_dedup"),
    )
    op.create_index(
        op.f("ix_notification_log_entra_user_id"),
        "notification_log",
        ["entra_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_log_run_id"), "notification_log", ["run_id"], unique=False
    )
    op.create_table(
        "user_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("refresh_jti", sa.String(length=64), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_session_refresh_jti"), "user_session", ["refresh_jti"], unique=True
    )
    op.create_index(op.f("ix_user_session_user_id"), "user_session", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_session_user_id"), table_name="user_session")
    op.drop_index(op.f("ix_user_session_refresh_jti"), table_name="user_session")
    op.drop_table("user_session")
    op.drop_index(op.f("ix_notification_log_run_id"), table_name="notification_log")
    op.drop_index(op.f("ix_notification_log_entra_user_id"), table_name="notification_log")
    op.drop_table("notification_log")
    op.drop_table("setting")
    op.drop_table("run")
    op.drop_table("exclusion")
    op.drop_index(op.f("ix_entra_user_upn"), table_name="entra_user")
    op.drop_index(op.f("ix_entra_user_entra_id"), table_name="entra_user")
    op.drop_table("entra_user")
    op.drop_index(op.f("ix_app_user_username"), table_name="app_user")
    op.drop_table("app_user")
    # ### end Alembic commands ###
